### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGrammar' of undefined

### ISSUE THREAD

**Issue by fohoizey** [mjmlio/atom-mjml-preview#1] opened 2016-12-22 08:41 UTC
Hello

I'm unable to load the preview package.

Here are the errors :+1:

Uncaught TypeError: Cannot read property 'getGrammar' of undefined
C:\Users\fohoizey\.atom\packages\mjml-preview\lib\mjml-preview.js:45
Show Stack Trace
The error was thrown from the mjml-preview package. You can help by creating an issue. Please explain what actions triggered this error.

> [Enter steps to reproduce below:]
> 
> 1. ...
> 2. ...
> 
> **Atom Version**: 1.12.7
> **Electron Version**: 1.3.13
> **System**: Unknown Windows Version
> **Thrown From**: [mjml-preview](https://github.com/mjmlio/atom-mjml-preview) package, v1.1.0
> 
> 
> ### Stack Trace
> 
> Uncaught TypeError: Cannot read property 'getGrammar' of undefined
> 
> ```
> At C:\Users\fohoizey\.atom\packages\mjml-preview\lib\mjml-preview.js:45
> 
> TypeError: Cannot read property 'getGrammar' of undefined
>     at Object.openPane (file:///C:/Users/fohoizey/.atom/packages/mjml-preview/lib/mjml-preview.js:45:38)
>     at atom-workspace.mjmlPreviewPreview (file:///C:/Users/fohoizey/.atom/packages/mjml-preview/lib/mjml-preview.js:38:101)
>     at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\fohoizey\AppData\Local\atom\app-1.12.7\resources\app.asar\src\command-registry.js:259:29)
>     at CommandRegistry.handleCommandEvent (C:\Users\fohoizey\AppData\Local\atom\app-1.12.7\resources\app.asar\src\command-registry.js:3:59)
>     at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\fohoizey\AppData\Local\atom\app-1.12.7\resources\app.asar\src\command-registry.js:160:19)
>     at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\fohoizey\AppData\Local\atom\app-1.12.7\resources\app.asar\src\atom-environment.js:1136:28)
>     at EventEmitter.outerCallback (C:\Users\fohoizey\AppData\Local\atom\app-1.12.7\resources\app.asar\src\application-delegate.js:319:25)
>     at emitTwo (events.js:106:13)
>     at EventEmitter.emit (events.js:191:7)
> ```
> 
> ### Commands
> 
> ```
>      -4:42.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
>      -2:24.6.0 core:paste (atom-text-editor.editor.is-focused)
>      -2:18.8.0 grammar-selector:show (atom-text-editor.editor.is-focused)
>   3x -2:08.9.0 mjml-preview:preview (atom-text-editor.editor.is-focused)
> ```
> 
> ### Config
> 
> ```json
> {
>   "core": {
>     "telemetryConsent": "no"
>   }
> }
> ```
> 
> ### Installed Packages
> 
> ```coffee
> # User
> atom-clock, v0.1.0 (active)
> language-mjml, v1.8.0 (active)
> linter, v1.11.18 (active)
> linter-mjml, v1.0.0 (active)
> mjml-preview, v1.1.0 (active)
> qolor, v0.4.1 (active)
> atom-dark-syntax, v0.27.0 (inactive)
> atom-dark-ui, v0.52.0 (inactive)
> atom-light-syntax, v0.28.0 (inactive)
> atom-light-ui, v0.45.0 (inactive)
> base16-tomorrow-dark-theme, v1.3.0 (inactive)
> base16-tomorrow-light-theme, v1.3.0 (inactive)
> one-dark-ui, v1.6.2 (active)
> one-light-ui, v1.6.2 (inactive)
> one-dark-syntax, v1.5.0 (active)
> one-light-syntax, v1.5.0 (inactive)
> solarized-dark-syntax, v1.0.5 (inactive)
> solarized-light-syntax, v1.0.5 (inactive)
> about, v1.7.0 (active)
> archive-view, v0.62.0 (active)
> autocomplete-atom-api, v0.10.0 (active)
> autocomplete-css, v0.13.1 (active)
> autocomplete-html, v0.7.2 (active)
> autocomplete-plus, v2.31.4 (active)
> autocomplete-snippets, v1.11.0 (active)
> autoflow, v0.27.0 (inactive)
> autosave, v0.23.1 (active)
> background-tips, v0.26.1 (active)
> bookmarks, v0.42.0 (active)
> bracket-matcher, v0.82.2 (active)
> command-palette, v0.39.0 (inactive)
> deprecation-cop, v0.54.1 (active)
> dev-live-reload, v0.47.0 (active)
> encoding-selector, v0.22.0 (active)
> exception-reporting, v0.40.0 (active)
> find-and-replace, v0.202.2 (inactive)
> fuzzy-finder, v1.4.0 (active)
> git-diff, v1.1.0 (active)
> go-to-line, v0.31.0 (inactive)
> grammar-selector, v0.48.2 (active)
> image-view, v0.60.0 (active)
> incompatible-packages, v0.26.1 (active)
> keybinding-resolver, v0.35.0 (active)
> line-ending-selector, v0.5.0 (active)
> link, v0.31.2 (inactive)
> markdown-preview, v0.158.8 (active)
> metrics, v1.1.2 (active)
> notifications, v0.65.1 (active)
> open-on-github, v1.2.1 (inactive)
> package-generator, v1.0.1 (inactive)
> settings-view, v0.243.1 (active)
> snippets, v1.0.4 (active)
> spell-check, v0.68.4 (active)
> status-bar, v1.4.1 (active)
> styleguide, v0.47.2 (active)
> symbols-view, v0.113.1 (inactive)
> tabs, v0.103.0 (active)
> timecop, v0.33.2 (active)
> tree-view, v0.210.0 (active)
> update-package-dependencies, v0.10.0 (active)
> welcome, v0.35.1 (active)
> whitespace, v0.35.0 (active)
> wrap-guide, v0.38.2 (active)
> language-c, v0.54.0 (active)
> language-clojure, v0.22.1 (active)
> language-coffee-script, v0.48.0 (active)
> language-csharp, v0.13.0 (active)
> language-css, v0.40.1 (active)
> language-gfm, v0.88.0 (active)
> language-git, v0.15.0 (active)
> language-go, v0.43.0 (active)
> language-html, v0.47.1 (active)
> language-hyperlink, v0.16.1 (active)
> language-java, v0.24.0 (active)
> language-javascript, v0.122.0 (active)
> language-json, v0.18.3 (active)
> language-less, v0.29.6 (active)
> language-make, v0.22.2 (active)
> language-mustache, v0.13.0 (active)
> language-objective-c, v0.15.1 (active)
> language-perl, v0.37.0 (active)
> language-php, v0.37.3 (active)
> language-property-list, v0.8.0 (active)
> language-python, v0.45.1 (active)
> language-ruby, v0.70.2 (active)
> language-ruby-on-rails, v0.25.1 (active)
> language-sass, v0.57.0 (active)
> language-shellscript, v0.23.0 (active)
> language-source, v0.9.0 (active)
> language-sql, v0.25.0 (active)
> language-text, v0.7.1 (active)
> language-todo, v0.29.1 (active)
> language-toml, v0.18.1 (active)
> language-xml, v0.34.12 (active)
> language-yaml, v0.27.1 (active)
> 
> # Dev
> No dev packages
> ```
> 
> 
Any idea of what to do ?

Thanks

**Comment by ngarnier** [comment] 2016-12-22 09:33
Hey @fohoizey, sorry for this issue. It seems to be a recurring issue with Atom packages, we'll look into it!

**Comment by joshhopkins** [comment] 2017-01-10 11:09
Same issue here.

**Comment by JeffCleverley** [comment] 2017-02-03 11:47
Same issue here

**Comment by ngarnier** [comment] 2017-02-13 15:55
Hello guys, I have an idea to solve this but I can't reproduce this error so I can't test it, could you help? Maybe by providing a MJML template where it happens.

A friend of mine tried reinstalling the package and it fixed it, can you try it to see if it solves the problem for you?

**Comment by JeffCleverley** [comment] 2017-02-14 06:48
I had previously uninstalled the package. As I have just updated Atom and a few other packages, I figured I would try this again.

Unfortunately, I am getting no preview and no error message, sorry.

https://github.com/mjmlio/atom-mjml-preview/issues/4

**Comment by ngarnier** [comment] 2017-02-14 08:55
Thanks for the update, this might be an unrelated issue which would also mean this one is fixed by reinstalling the package/updating Atom, we'll figure it out!

**Closed as completed** 2018-04-12 08:00 UTC
Labels: bug
